# permissions for end users to edit groups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: group-editor-role
rules:
- apiGroups:
  - keycloak.schella.network
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.schella.network
  resources:
  - groups/status
  verbs:
  - get
