# permissions for end users to view groups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: group-viewer-role
rules:
- apiGroups:
  - keycloak.schella.network
  resources:
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.schella.network
  resources:
  - groups/status
  verbs:
  - get
