---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - keycloak.schella.network
  resources:
  - clients
  - groups
  - keycloakinstanceconfigs
  - realmroles
  - realms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.schella.network
  resources:
  - clients/finalizers
  - groups/finalizers
  - keycloakinstanceconfigs/finalizers
  - realmroles/finalizers
  - realms/finalizers
  verbs:
  - update
- apiGroups:
  - keycloak.schella.network
  resources:
  - clients/status
  - groups/status
  - keycloakinstanceconfigs/status
  - realmroles/status
  - realms/status
  verbs:
  - get
  - patch
  - update
