---
apiVersion: keycloak.schella.network/v1alpha1
kind: Client
metadata:
  labels:
    app.kubernetes.io/name: keycloak-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: client-minimal
spec:
  realmRef:
    name: realm-sample
  clientId: client-minimal
---
apiVersion: keycloak.schella.network/v1alpha1
kind: Client
metadata:
  labels:
    app.kubernetes.io/name: keycloak-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: client-sample
spec:
  realmRef:
    name: realm-sample
    namespace: default  # Optional, defaults to same namespace
  clientId: client-sample
  enabled: true
  name: "My Application"
  description: "My application"
  rootUrl: https://domain.example
  baseUrl: https://domain.example/fallback
  publicClient: false
  standardFlowEnabled: true
  directAccessGrantsEnabled: true
  implicitFlowEnabled: false
  serviceAccountsEnabled: false
  oauth2DeviceAuthorizationGrantEnabled: false
  redirectUris:
    - "https://myapp.example.com/callback"
  postLogoutRedirectUris:
    - "https://myapp.example.com/logout"
    - "http://localhost:8080/logout"
  webOrigins:
    - "+"
  roles:
    - name: admin
      description: Full administrative access to all system resources
    - name: editor
